### ISSUE TITLE
QGIS crashing

### ISSUE THREAD

**Issue by Anafi** [OpenDigitalWorks/Rcl-topology-cleaner#16]
Sometimes when closing the plugin QGIS crashes. I suspect that this is caused by signals that have not been disconnected.

**Comment by jorgegil** [comment]
I checked and you don't have connections to QGIS signals. All connections are within the plugin, so in theory should be ok.
So far unable to reproduce. Have you found a consistent pattern for the crash?

**Comment by Anafi** [comment]
No QGIS crashing for me either... I will close the issue for now...
