### ISSUE TITLE
Tries to connect to databases that are not related to the layers

### ISSUE THREAD

**Issue by jorgegil** [OpenDigitalWorks/Rcl-topology-cleaner#26]
When I start the tool I get a pop up asking for credentials to a specific PostGIS database.
The current layers are in shape files, so it's strange to get such errors because it has nothing to do with the user's data.
Not sure why this has to be done before knowing if the database is at all required and which one, i.e. the layers are indeed in a database.

In this particular case, the connection exists and works, but the database name is "phd_work" and the connection name "phd work" are different. Maybe the tool assumes the connection name is the same as dbname?
From the stack:
db_manager.db_plugins.plugin.ConnectionError: FATAL:  database "phd work" does not exist
The call is made when updating the dbsettings dialog in line 565 of road_network_cleaner.py, and the popSchemas() function in line 268 tries to connect.

**Comment by Anafi** [comment]
Fixed! Indeed I assumed the same db name and connection name. Jorge can you confirm?

**Comment by jorgegil** [comment]
It's now working as far as loading databases and schema names.
Haven't tested writing to the database so far.
