### ISSUE TITLE
Closed lines cannot be removed but must be split instead

### ISSUE THREAD

**Issue by jorgegil** [OpenDigitalWorks/Rcl-topology-cleaner#28]
Currently the tool deals with closed line strings by removing them. With OSM data this results in a very disconnected network as many actual road elements are represented as closed line strings.
While many are polygons delimiting pedestrian areas, many more are roundabouts, and other small features. Running the tool on the sample OSM data results in a very wrong network.

The ideal solution would be to filter out what are relevant closed lines and which ones are not. But the tool must be generic, not OSM specific. So the solution is to accept all as valid and split them into multiple lines.

This step should be one of the first. Must come before splitting lines at intersection and merging them again.

**Comment by Anafi** [comment]
Fixed algorithm. Only closed polylines that do not share any vertex with any other line are removed
