### ISSUE TITLE
Crashes on second consecutive run

### ISSUE THREAD

**Issue by jorgegil** [OpenDigitalWorks/Rcl-topology-cleaner#29]
if the plugin is run for a second time immediately after the first at the end it crashes QGIS!

A symptom is the progress bar "twitching", i.e. going slightly back an forth as it moves. To me this is a sign that a second thread is running at the same time. Then, when the first one finishes and the plugin cleans up the second thread falls apart.

I think the thread is only being stopped but does not really get removed, and when you create a new one with the same name, both get started.
Possible solutions:
* create only one thread object in the __init__ function that runs once when the plugin is loaded  by QGIS. Then this one is called later.
* use del self.cleaning instead of self.cleaning = None. It should be the same, but might not because you have a global member of the class that remains. https://stackoverflow.com/questions/6146963/when-is-del-useful-in-python

But this needs to be tested.

**Comment by Anafi** [comment]
The problem was in the **init()** function in my main class. I was creating the dialogue objects there with: 

```self.dlg = RoadNetworkCleanerDialog()```
```self.dbsettings_dlg = DbSettingsDialog()```
```self.clsettings_dlg = ClSettingsDialog()```

Replacing the above with None and creating the dialogue objects in the **run()** method solved the issue.

**Comment by jorgegil** [comment]
Looks like it...
This way the entire dialog is destroyed and constructed every time, rather than reused.
I guess the old thread was still there and being restarted again every time.
